# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://berlin.endler.cc"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = false     # has chinese/japanese/korean ? # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡\æ—¥æ–‡\éŸ©æ–‡
paginate = 3              # Number of articles displayed on the homepage  # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
rssLimit = 20             # Limit Entry Count to Rss file # é™åˆ¶ Rss æ–‡ç« è¾“å‡ºæ•°é‡
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name â†“        # é»˜è®¤ä¸ºä¸‹é¢é…ç½®çš„author.name â†“

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use

showAuthorCard = false


[author]                  # essential                     # å¿…éœ€
  name = ""

[sitemap]                 # essential                     # å¿…éœ€
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[languages.en]
  title = "Getting settled in Berlin ğŸ»"
  languageCode = "en"
  languageName = "English"
  contentDir = "content/en"
  weight = 1
  customFooter = "â¤ from Berlin "

[languages.de]
  title = "FuÃŸ fassen in Berlin ğŸ»"
  languageCode = "de"
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 2
  customFooter = "â¤ aus Berlin "


[params]
  since = "2020"            # Site creation time          # ç«™ç‚¹å»ºç«‹æ—¶é—´
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # ç«™ç‚¹ä¿¡æ¯ï¼ˆå¯é€‰ï¼Œä¸éœ€è¦çš„å¯ä»¥ç›´æ¥æ³¨é‡Šæ‰ï¼‰
  # logoTitle = "Setting foot in Berlin"        # default: the title value    # é»˜è®¤å€¼: ä¸Šé¢è®¾ç½®çš„titleå€¼
  keywords = ["Berlin", "migration","setting foot","Imigration"]
  description = "Let's make others feel welcome in Berlin"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # ä¸€äº›å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½ï¼Œåœ¨ archetypes/default.md æŸ¥çœ‹æ›´å¤šä¿¡æ¯ã€‚
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                                            # æ˜¯å¦å¼€å¯ç›®å½•
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # æ˜¯å¦å¯ç”¨PhotoSwipeï¼ˆå›¾ç‰‡å¯ç‚¹å‡»ï¼‰
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  showMenuLanguageChooser = true
  showAuthorInfo = false
  

  [params.social]                                         # ç¤¾äº¤é“¾æ¥
    # a-email = "mailto:your@email.com"
    # b-stack-overflow = "http://localhost:1313"
    # c-twitter = "http://localhost:1313"
    # d-facebook = "http://localhost:1313"
    # e-linkedin = "http://localhost:1313"
    # f-google = "http://localhost:1313"
    # g-github = "http://localhost:1313"
    # h-weibo = "http://localhost:1313"
    # i-zhihu = "http://localhost:1313"
    # j-douban = "http://localhost:1313"
    # k-pocket = "http://localhost:1313"
    # l-tumblr = "http://localhost:1313"
    # m-instagram = "http://localhost:1313"
    # n-gitlab = "http://localhost:1313"
    # o-goodreads = "http://localhost:1313"
    # p-coding = "http://localhost:1313"
    # q-bilibili = "http://localhost:1313"
    # r-codeforces = "http://localhost:1313"
    # s-mastodon = "http://localhost:1313"
    # t-youtube = "http://localhost:1313"
    # u-twitch = "http://localhost:1313"
